/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemoMxRouteImport } from './routes/demo-mx'
import { Route as FullRouteImport } from './routes/full'
import { Route as GraciasRouteImport } from './routes/gracias'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMxRoute = DemoMxRouteImport.update({
  id: '/demo-mx',
  path: '/demo-mx',
  getParentRoute: () => rootRouteImport,
} as any)
const FullRoute = FullRouteImport.update({
  id: '/full',
  path: '/full',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-mx': typeof DemoMxRoute
  '/full': typeof FullRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-mx': typeof DemoMxRoute
  '/full': typeof FullRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/demo-mx': typeof DemoMxRoute
  '/full': typeof FullRoute
  '/gracias': typeof GraciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/demo-mx' | '/full' | '/gracias'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/demo-mx' | '/full' | '/gracias'
  id: '__root__' | '/' | '/demo' | '/demo-mx' | '/full' | '/gracias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DemoMxRoute: typeof DemoMxRoute
  FullRoute: typeof FullRoute
  GraciasRoute: typeof GraciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-mx': {
      id: '/demo-mx'
      path: '/demo-mx'
      fullPath: '/demo-mx'
      preLoaderRoute: typeof DemoMxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full': {
      id: '/full'
      path: '/full'
      fullPath: '/full'
      preLoaderRoute: typeof FullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DemoMxRoute: DemoMxRoute,
  FullRoute: FullRoute,
  GraciasRoute: GraciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
